#!/usr/bin/python3
from sys import argv
def biggestFactor(num):
    result = 1
    for i in range(2, num + 1, 1):
        if(num % i == 0):
            result = num/i
            break
    return result
if len(argv) != 2:
    print("{} <file>".format(argv[0]))
with open(argv[1]) as factor_file:
    for line in factor_file:
        line = int(line)
        largest_factor = biggestFactor(line)
        print("{:d}={:d}*{:d}".format(line, largest_factor, int(line / largest_factor)))
